### ISSUE TITLE
[Dataset View Pages] Dataset breadcrumbs include top-level organisations

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/ckanext-datawagovautheme#14]
We only want the direct parent organisation to show (e.g. DPIRD), not the top-level parent (e.g. WA State Govt).

UAT
![screen shot 2019-01-23 at 13 58 34](https://user-images.githubusercontent.com/5944358/51591582-6418a380-1f28-11e9-9f11-f51064cea3ed.png)

PROD
![screen shot 2019-01-23 at 13 58 27](https://user-images.githubusercontent.com/5944358/51591584-6418a380-1f28-11e9-9755-b1e42753c1dc.png)

Related to: https://github.com/datawagovau/ckanext-datawagovautheme/issues/13

**Comment by keithamoss** [comment]
On second thoughts, let's keep this behaviour.
