### ISSUE TITLE
[Dataset View Page] The sidebar elements are shown before the dataset information

### ISSUE THREAD

**Issue by keithmoss** [datawagovau/ckanext-datawagovautheme#30]
https://catalogue.data.wa.gov.au/dataset/city-of-perth-car-parks
https://uat.landgate.links.com.au/dataset/city-of-perth-car-parks

Responsive design issue on mobile devices.

The elements that normally sit in the sidebar (organisation name, description, social links) are displayed above the dataset description and metadata. We should restore the order of elements to match PROD - i.e. so that the dataset information comes first.

UAT
https://user-images.githubusercontent.com/1672960/52451786-5e070180-2b7b-11e9-9927-e030ea5507ed.png

PROD
https://user-images.githubusercontent.com/1672960/52451792-62cbb580-2b7b-11e9-8c72-134620b39a3a.png

**Comment by krupalip** [comment]
the position has been changed in base code to fix bootstrap3 issues.
ref: https://github.com/ckan/ckan/pull/3767/commits/00e8dc5caa1029f978dc0525b3996f2bc8330c61
PR: https://github.com/ckan/ckan/pull/3767
@keithamoss do you still want to swap back?

**Comment by keithamoss** [comment]
@krupalip Good sleuthing out the original issue there!

In this case let's leave it as it is now

**Comment by krupalip** [comment]
ok thanks
